# Railway deployment config for KAI monorepo
[build]
  dockerfile = "Dockerfile"
  buildCommand = ""
  startCommand = "uvicorn midas-mcp-server.server:app --host 0.0.0.0 --port $PORT"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"
